version: "3.9"

services:
  web:
    build: .
    container_name: easepark_web
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
