"""Add lot_type and amenities to ParkingLot

Revision ID: 4feb83e892d9
Revises: 756ca7d39242
Create Date: 2026-04-07 23:18:23.877064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4feb83e892d9'
down_revision = '756ca7d39242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_column('amenities')
        batch_op.drop_column('lot_type')

    # ### end Alembic commands ###
