"""Add indexes for performance optimization

Revision ID: 6177ade323cb
Revises: 07f466c95901
Create Date: 2026-03-31 20:50:21.089497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6177ade323cb'
down_revision = '07f466c95901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_lot_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_lot_pin_code'), ['pin_code'], unique=False)

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_spot_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_spot_status'), ['status'], unique=False)
        batch_op.create_index('ix_spot_lot_status', ['lot_id', 'status'], unique=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_booking_timestamp'), ['booking_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_spot_id'), ['spot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reservation_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_vehicle_number'), ['vehicle_number'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_member_since'), ['member_since'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_pin_code'), ['pin_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_pin_code'))
        batch_op.drop_index(batch_op.f('ix_users_member_since'))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_vehicle_number'))
        batch_op.drop_index('ix_reservation_user_status')
        batch_op.drop_index(batch_op.f('ix_reservation_user_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_status'))
        batch_op.drop_index(batch_op.f('ix_reservation_spot_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_booking_timestamp'))

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_index('ix_spot_lot_status')
        batch_op.drop_index(batch_op.f('ix_parking_spot_status'))
        batch_op.drop_index(batch_op.f('ix_parking_spot_lot_id'))

    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_lot_pin_code'))
        batch_op.drop_index(batch_op.f('ix_parking_lot_is_active'))

    # ### end Alembic commands ###
