"""Add otp_expires_at to reservation

Revision ID: 756ca7d39242
Revises: 6177ade323cb
Create Date: 2026-04-07 03:36:16.542629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756ca7d39242'
down_revision = '6177ade323cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('otp_expires_at')

    # ### end Alembic commands ###
