"""add vehicle model

Revision ID: d90da2855fd6
Revises: 4feb83e892d9
Create Date: 2026-06-21 06:52:56.328350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd90da2855fd6'
down_revision = '4feb83e892d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_member_since'))
        batch_op.drop_index(batch_op.f('ix_vehicles_pin_code'))
        batch_op.drop_index(batch_op.f('ix_vehicles_role'))
        batch_op.drop_constraint(batch_op.f('vehicles_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('vehicles_phone_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('vehicles_username_key'), type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('username')
        batch_op.drop_column('full_name')
        batch_op.drop_column('total_bookings')
        batch_op.drop_column('pin_code')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('password_reset_otp')
        batch_op.drop_column('role')
        batch_op.drop_column('address')
        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('member_since')
        batch_op.drop_column('email_verification_otp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('member_since', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_reset_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pin_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_bookings', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('vehicles_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('vehicles_phone_number_key'), ['phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('vehicles_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_vehicles_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_pin_code'), ['pin_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_member_since'), ['member_since'], unique=False)

    # ### end Alembic commands ###
